# Generated by Django 3.1.4 on 2020-12-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201231_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='first_line',
            new_name='first_name',
        ),
    ]
